apiVersion: apps/v1
kind: Deployment
metadata:
    name: goserver
spec:
    replicas: 1
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
                - name: goserver
                  image: fernandojpessoa/goserver:0.1.6
                  imagePullPolicy: IfNotPresent
                  resources:
                    requests:
                      memory: "128Mi"
                      cpu: "128m"
                    limits:
                      memory: "128Mi"
                      cpu: "256m"
   