name: Deploy
on:
    push:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:

        - uses: actions/checkout@v2

        - name: Docker meta
          id: docker_meta
          uses: crazy-max/ghaction-docker-meta@v1
          with:
            images: fernandojpessoa/goserver
            tag-sha: true


        - name: QEMU
          uses: docker/setup-qemu-action@v1

        - name: Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to Dockerhub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME}}
            password: ${{ secrets.DOCKERHUB_TOKEN}}

        - name: Bump version and push tag
          id: tagging
          uses: mathieudutour/github-tag-action@v4.5
          with:
            github_token: ${{ secrets.TOKEN_GIT }}

        - name: Build and push
          id: docker_build 
          uses: docker/build-push-action@v2
          with:
            push: true
            context: .
            file: ./Dockerfile
            platforms: linux/amd64
            tags: fernandojpessoa/goserver:${{ steps.tagging.outputs.new_version }}

        - name: Install doctl
          uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DIGITALOCEAN_TOKEN }}

        - name: Setup kubectl
          uses: matootie/dokube@v1.3.2
          with:
            personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
            clusterName: k8s-ci-cd

        - name: set deployment image
          run: kubectl set image deployment goserver goserver=fernandojpessoa/goserver:${{ steps.tagging.outputs.new_version }}